Develop
joeyliao127/Taipei_day_trip pull request #3
Opened 2023-09-06 08:40 UTC by joeyliao127

aka Joey 廖致皓
url：http://44.219.72.138:3000/

2023-09-06 10:19 UTC, cwpeng requested changes
Small issue: your layout exceeds screen width, slightly.

2023-09-06 15:44 UTC, cwpeng requested changes
The root cause is layout did exceed screen width, so that some elements are cutted without scrolling. Just hiding scrollbar does not resolve that.

2023-09-06 23:15 UTC, joeyliao127 commented
是的，我昨天花了兩個多小時再確認尺寸，在設計時基本上已經考量到最大寬度1200px。
也確認了寬度都沒有超過1200px。但不知道什麼原因，在圖片Load到網頁時就會出現水平移動軸，現在將body的overflow: hidden拿掉，
也不知道為什麼就沒有出現。

2023-09-07 11:22 UTC, joeyliao127 commented
Hi 彭彭老師，我發現是wrapper的width設定出現了問題，導致水平移動軸的產生，後來決定把wrapper拿掉，因為結構上有點多餘，再麻煩幫忙檢查，感謝！

2023-09-07 13:25 UTC, cwpeng approved these changes
Good. Done.

2023-09-07 13:36 UTC, merged